# config/emotion_config.yaml

# -------------------------------------------------------------------
# Emotion 분류 모델 설정
# -------------------------------------------------------------------
model:
  name: "google/electra-small-discriminator"
  num_labels: 28

# -------------------------------------------------------------------
# 데이터 경로 설정
# -------------------------------------------------------------------
data:
  raw_dir: "data/raw/go_emotions_simplified"
  processed_dir: "data/processed/go_emotions_simplified"
  train_split: "train"
  validation_split: "validation"
  test_split: "test"

# -------------------------------------------------------------------
# 학습 하이퍼파라미터
# -------------------------------------------------------------------
train:
  output_dir: "outputs/emotion"
  epochs: 5
  train_batch_size: 32
  eval_batch_size: 64
  learning_rate: 2e-5
  eval_strategy: "epoch"
  save_strategy: "epoch"
  best_metric: "f1_macro"

# -------------------------------------------------------------------
# 추론(inference) 설정
# -------------------------------------------------------------------
inference:
  threshold: 0.85
  label_list:
    - admiration
    - amusement
    - anger
    - annoyance
    - approval
    - caring
    - confusion
    - curiosity
    - desire
    - disappointment
    - disapproval
    - disgust
    - embarrassment
    - excitement
    - fear
    - gratitude
    - grief
    - joy
    - love
    - nervousness
    - optimism
    - pride
    - realization
    - relief
    - remorse
    - sadness
    - surprise
    - neutral

# -------------------------------------------------------------------
# 토크나이저 최대 시퀀스 길이
# -------------------------------------------------------------------
max_length: 128
