# config/intent_config.yaml

# ---
# Configuration for L.U.N.A Intent Classification
# Based on clinc_oos (plus) dataset and BERT-tiny model
# ---

model:
  name: "google/bert_uncased_L-2_H-128_A-2"
  num_labels: 151

data:
  raw_dir: "data/raw/clinc_oos"
  processed_dir: "data/processed/clinc_oos"
  train_split: "train"
  validation_split: "validation"
  test_split: "test"

train:
  output_dir: "outputs/intent"
  epochs: 5
  train_batch_size: 32
  eval_batch_size: 64
  learning_rate: 5e-5
  eval_strategy: "epoch"
  save_strategy: "epoch"
  best_metric: "accuracy"

inference:
  label_list: []

max_length: 64
