# config/multiintent_config.yaml

# ---
# Configuration for L.U.N.A Intent Classification
# Based on multi_clinc dataset and BERT-tiny model
# ---

model:
  name: "google/bert_uncased_L-2_H-128_A-2"
  num_labels: 147

data:
  raw_dir: "data/raw/clinc_multi"
  processed_dir: "data/processed/clinc_multi"
  train_split: "train"
  validation_split: "validation"
  test_split: "test"

train:
  output_dir: "outputs/intent"
  epochs: 30
  train_batch_size: 32
  eval_batch_size: 64
  learning_rate: 5e-5
  eval_strategy: "epoch"
  save_strategy: "epoch"
  best_metric: "f1"

inference:
  threshold: 0.5
  label_list: []

max_length: 64
